### ISSUE TITLE
README needs improving 🎶

### ISSUE THREAD

**Issue by LiCern** [fac20/week4-BCLN-project#26]
It would be helpful if you gave some guidance on how to run your code in particular

**Comment by akomiqaia** [comment]
The read me is SICK. Good job everyone. The section about installing dependencies could be more clear. 

Give terminal commands into `code snippets` so it is clear what people need to do. 

At the moment some people might know what to do but in the future when the project gets bigger you might want to have step by step installation guide. 

Also, your read me doesn't tell me how to run the tests.
