### ISSUE TITLE
public/script.js POST fetch method

### ISSUE THREAD

**Issue by akomiqaia** [fac20/week4-BCLN-project#29]
While trying to submit it just hangs doesn't show me anything but if  I refresh the page my data appears as a list. Not sure what is causing it but bellow comments might help.

Unhandled `fetch` request in public/script.js file line 49. `fetch` request always returns a promise and promises have to be solved or rejected. Never forget `.catch` for error handling. Error handling is essential.

Alternatively instead of sending post request this way you can have a look on `form` action and methods. But on the server-side, you might need to extract data different way that was shown in node workshop.
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data

https://github.com/oliverjam/node-http-server

```javascript
const data = new URLSearchParams(body);
const name = data.get("name");
console.log(name); // oli
```

**Comment by amberrignell** [comment]
Thanks for the comment, we've just included a location.reload() in the fetch request to address this issue
