### ISSUE TITLE
MIME types of your style.css not being supported 

### ISSUE THREAD

**Issue by trishtracking** [fac20/week4-BCLN-project#32]
Getting the following error on index.html: 

Refused to apply style from 'http://127.0.0.1:5500/public/public/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I think you've not fully split out the types, you may need to split it on '/' as well... but not certain on that!

**Comment by amberrignell** [comment]
Weird ... we don;t get that error. But we also never got round to writing any css so the entire file could just be deleted
